[tox]

requires =
    tox>4

envlist=
    py{310,311,312}-dj4.2-test
    py{310,311,312}-dj5.0-test
    py{310,311,312,313}-dj5.1-test
    py{310,311,312,313,314}-dj5.2-test
    py{312,313,314}-dj6.0-test
    py{310,311,312,313,314}-ruff
    py314-djmaster-test,

[testenv]
basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12
    py313: python3.13
    py314: python3.14

pip_pre = true

deps =
    ruff

    dj4.2: Django>=4.2,<4.3
    dj5.0: Django>=5.0,<5.1
    dj5.1: Django>=5.1,<5.2
    dj5.2: Django>=5.2,<5.3
    dj6.0: Django>=6.0,<6.1
    djmaster: https://github.com/django/django/archive/refs/heads/main.zip

allowlist_externals = *

commands =
    test: ./run_test.py
    ruff: ruff check .
